# Generated by Django 4.2.3 on 2023-08-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
