# Generated by Django 4.2.3 on 2023-08-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0005_group_alter_mymusicappuser_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
